import { createClient } from '@supabase/supabase-js'
import twilio from 'twilio'
import { generateReportPdf } from './generateReport'
import {
  pullInternalMetricsWithDelta,
  pullMarketContext,
  pullCensusContext,
  findB2BOutreachTargets,
  computeBellaveGoScore,
} from './consultingMetrics'
import { generateReportNarrative } from './generateReportNarrative'
import { cadenceDaysForTier, periodLabel } from './reportCadence'
import type { ConsultingReport, ServiceAreaPoint } from './consultingReport'
import {
  pullMarketOpportunity,
  buildLocalEconomyFromCensus,
  pullRegulatoryWatch,
} from './consultingExtras'
import { OFFICE_MGR_TIERS, CONCIERGE_TIERS } from './pricing'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)
const twilioClient = twilio(process.env.TWILIO_ACCOUNT_SID!, process.env.TWILIO_AUTH_TOKEN!)

export type RunnerProfile = {
  user_id: string
  business_name?: string | null
  business_type?: string | null
  owner_phone?: string | null
  owner_first_name?: string | null
  twilio_number?: string | null
  service_area?: string | null
  zip_code?: string | null
  google_place_id?: string | null
  plan_tier?: string | null
  is_active?: boolean | null
  welcome_report_at?: string | null
  last_consulting_report_at?: string | null
}

export type RunOutcome = {
  user_id: string
  status: 'generated' | 'skipped' | 'error'
  reportType?: 'welcome' | 'periodic'
  reportId?: string
  pdfUrl?: string
  reason?: string
}

function buildMethodology(reported: number, estimated: number, reportedCount: number, estimatedCount: number): string {
  const total = reported + estimated
  const reportedPct = total > 0 ? Math.round((reported / total) * 100) : 0
  const revenueDisclosure = total > 0
    ? `Revenue figures: $${Math.round(reported).toLocaleString()} from your reported job amounts (${reportedCount} jobs, ${reportedPct}%) plus $${Math.round(estimated).toLocaleString()} estimated from trade-average tickets where amounts weren't reported (${estimatedCount} jobs, ${100 - reportedPct}%). Estimates auto-replace with real numbers as you reply to the post-job revenue text. `
    : ''

  return (
    'Internal metrics pulled from this account\'s BellAveGo call_logs + jobs over the cadence window, with the prior-period of the same length used for deltas. ' +
    revenueDisclosure +
    'Local market data from Google Places (competitors, ratings, geographic positioning) and US Census ACS 2022 5-year (homeowner counts, median income, median home age) for the customer\'s primary ZIP. ' +
    'BellAveGo Score blends answer rate (25%), booking conversion (30%), AI response-time baseline (15%), and avg-ticket-vs-trade-anchor pricing power (30%). ' +
    'B2B outreach targets are real businesses pulled from Google Places — commercial properties only (TCPA-safe). ' +
    'Narrative + opportunity ranking + action plan generated by the BellAveGo AI engine, grounded in the inputs above. Every dollar figure is derived from the contractor\'s own numbers or from cited market data — no industry-aggregate claims.'
  )
}

/**
 * Generate ONE consulting report end-to-end for a single contractor:
 *   1. Pull internal metrics (current + prior period for deltas)
 *   2. Pull Google Places market context (competitors, ratings, distance, map pins)
 *   3. Pull US Census demographics for the primary ZIP
 *   4. Pull B2B outreach targets via Google Places
 *   5. Compute BellAveGo Score
 *   6. Call Claude Sonnet to write exec summary + 3 opportunities + 5-step action plan + strengths + gaps + upsells
 *   7. Render PDF via @react-pdf/renderer
 *   8. Upload PDF to Supabase Storage
 *   9. Insert row into consulting_reports (payload = full ConsultingReport)
 *  10. Update profiles.last_consulting_report_at (and welcome_report_at if first)
 *  11. SMS contractor with download link
 */
export async function generateAndDeliverReport(
  profile: RunnerProfile,
  reportType: 'welcome' | 'periodic',
): Promise<RunOutcome> {
  const userId = profile.user_id
  const businessName = profile.business_name || 'Your Business'
  const businessType = profile.business_type || 'home services'
  const serviceArea = profile.service_area || profile.zip_code || 'your local area'
  const primaryZip = (profile.zip_code || '').toString().replace(/\D/g, '').slice(0, 5)
  const firstName = profile.owner_first_name || splitFirstName(businessName)

  const cadenceDays = cadenceDaysForTier(profile.plan_tier) ?? 90
  // For welcome reports we use a 30-day lookback even though there's no data —
  // keeps deltas sensible (current=zero, prior=zero, delta=0).
  const lookbackDays = reportType === 'welcome' ? 30 : cadenceDays

  let metrics, market, census, outreach
  try {
    metrics = await pullInternalMetricsWithDelta(userId, lookbackDays)
    market = await pullMarketContext(profile)
    census = await pullCensusContext(primaryZip)
    outreach = await findB2BOutreachTargets(profile)
  } catch (e) {
    return { user_id: userId, status: 'error', reason: `data pull: ${(e as Error).message}` }
  }

  const score = computeBellaveGoScore(metrics.current, market)

  let narrative
  try {
    narrative = await generateReportNarrative({
      businessName,
      businessType,
      serviceArea,
      primaryZip,
      reportType,
      metrics,
      market,
      census,
      outreach,
      bellaveGoScore: score,
    })
  } catch (e) {
    return { user_id: userId, status: 'error', reason: `narrative: ${(e as Error).message}` }
  }

  // Build the full ConsultingReport payload — same shape sales page shows
  const windowEnd = new Date()
  const m = metrics.current
  const reportId = crypto.randomUUID()

  // Map points: stylized x/y fallback for the SVG renderer when no Google data,
  // but mapCenter + real lat/lng for the Static Maps API call.
  const points: ServiceAreaPoint[] = market.mapPoints.map((p, i) => ({
    kind: p.kind,
    label: p.label,
    x: p.kind === 'business' ? 50 : 28 + (i * 12) % 50,
    y: p.kind === 'business' ? 50 : 30 + (i * 17) % 40,
    lat: p.lat,
    lng: p.lng,
    note: p.name ? `${p.name}${p.rating ? ` · ★${p.rating.toFixed(1)}` : ''}${p.distanceMi ? ` · ${p.distanceMi} mi` : ''}` : undefined,
  }))

  // Census-derived addressable revenue (defensible heuristic: avg trade spend per
  // home per year × homeowner count ÷ 12). Set to 0 if no Census data.
  const annualSpendPerHome = tradeAnnualSpend(businessType)
  const addressableMonthly = census
    ? Math.round((census.homeownersInArea * annualSpendPerHome) / 12)
    : 0
  const pctHvacOver15 = census
    ? Math.max(0.15, Math.min(0.65, census.medianHomeAge / 80))
    : 0

  const report: ConsultingReport = {
    meta: {
      businessName,
      businessType,
      ownerName: firstName,
      period: periodLabel({ reportType, planTier: profile.plan_tier, windowEnd }),
      serviceArea: [primaryZip].filter(Boolean),
      primaryZip,
      metroLabel: profile.service_area || serviceArea,
      generatedAt: windowEnd.toISOString().slice(0, 10),
      reportNumber: `BAG-${windowEnd.getFullYear()}-Q${Math.floor(windowEnd.getMonth() / 3) + 1}-${reportId.slice(0, 6).toUpperCase()}`,
    },
    performance: {
      callsAnswered: m.callsAnswered,
      callsAnsweredDelta: metrics.delta.callsAnswered,
      jobsBooked: m.jobsBooked,
      jobsBookedDelta: metrics.delta.jobsBooked,
      revenue: m.totalRevenue,
      revenueDelta: metrics.delta.totalRevenue,
      avgTicket: m.avgJobValue,
      avgTicketDelta: metrics.delta.avgJobValue,
      callsSaved: m.callsSavedAfterHours,
      answerRate: m.answerRate,
    },
    bellaveScore: score,
    executiveSummary: narrative.executiveSummary,
    opportunities: narrative.opportunities,
    marketScan: {
      homeownersInArea: census?.homeownersInArea ?? 0,
      medianIncome: census?.medianIncome ?? 0,
      medianHomeAge: census?.medianHomeAge ?? 0,
      pctHvacOver15Yrs: pctHvacOver15,
      addressableRevenueMonthly: addressableMonthly,
      seasonalSignal: narrative.seasonalSignal,
    },
    upsells: narrative.upsells,
    competitive: {
      competitors: market.topCompetitors.map((c) => ({
        name: c.name,
        rating: c.rating,
        reviewCount: c.reviewCount,
        distance: c.distanceMi > 0 ? `${c.distanceMi} mi` : '—',
      })),
      yourRating: market.yourRating ?? 0,
      yourReviewCount: market.yourReviewCount ?? 0,
      marketAvgRating: market.avgCompetitorRating,
      marketAvgReviewCount: market.marketAvgReviewCount,
      yourRank: market.yourRank,
      totalCompetitors: market.totalCompetitorsRanked,
      strengths: narrative.competitiveStrengths,
      gaps: narrative.competitiveGaps,
    },
    serviceAreaMap: {
      centerLabel: serviceArea,
      points,
    },
    outreachTargets: outreach,
    actionPlan: narrative.actionPlan,
    methodology: buildMethodology(
      m.revenueReported,
      m.revenueEstimated,
      m.jobsWithReportedRevenue,
      m.jobsWithEstimatedRevenue,
    ),
  }

  // ── TIER-GATED ENHANCEMENTS (Pro + Elite) ──────────────────────
  // Pro and Elite contractors get extra sections. Every datum here is
  // sourced from public APIs / hardcoded fact tables — no fabrication.
  // If a section's data source returns nothing, the optional field
  // stays undefined and the PDF renderer omits it cleanly.
  const tierSlug = (profile.plan_tier || '').toLowerCase()
  const isPro   = OFFICE_MGR_TIERS.has(tierSlug)   // includes Elite by design (matches existing gates)
  const isElite = CONCIERGE_TIERS.has(tierSlug)

  if (isPro || isElite) {
    try {
      report.marketOpportunity = await pullMarketOpportunity({
        trade: businessType,
        primaryZip,
        homeownersInArea: census?.homeownersInArea ?? null,
        medianHomeAgeYears: census?.medianHomeAge ?? null,
      })
    } catch (e) {
      console.warn('marketOpportunity pull failed (non-fatal):', (e as Error).message)
    }

    if (census) {
      report.localEconomy = buildLocalEconomyFromCensus({
        population: census.homeownersInArea ? census.homeownersInArea * 2.5 : null, // ACS avg household size ≈ 2.5
        medianIncome: census.medianIncome ?? null,
        medianHomeAge: census.medianHomeAge ?? null,
        homeownersInArea: census.homeownersInArea ?? null,
      })
    }
  }

  if (isElite) {
    report.regulatoryWatch = pullRegulatoryWatch(businessType)
  }

  // 7. Render PDF
  let pdfBuffer: Buffer
  try {
    pdfBuffer = await generateReportPdf(report)
  } catch (e) {
    return { user_id: userId, status: 'error', reason: `pdf: ${(e as Error).message}` }
  }

  // 8. Upload to Storage
  const filePath = `${userId}/${reportId}.pdf`
  const { error: uploadErr } = await supabase
    .storage
    .from('consulting-reports')
    .upload(filePath, pdfBuffer, { contentType: 'application/pdf', upsert: false })
  if (uploadErr) {
    return { user_id: userId, status: 'error', reason: `upload: ${uploadErr.message}` }
  }
  const { data: pub } = supabase.storage.from('consulting-reports').getPublicUrl(filePath)
  const pdfUrl = pub.publicUrl

  // 9. Insert DB row
  const titleStr =
    reportType === 'welcome'
      ? 'Welcome — Your First BellAveGo Report'
      : `${quarterLabel(windowEnd)} Performance Report`
  const { error: insertErr } = await supabase.from('consulting_reports').insert({
    id: reportId,
    user_id: userId,
    profile_id: userId,
    title: titleStr,
    client_name: businessName,
    period_label: report.meta.period,
    report_type: reportType,
    cadence_tier: profile.plan_tier ?? null,
    pdf_url: pdfUrl,
    pdf_path: filePath,
    payload: report,
    bellavego_score: score.composite,
    generated_by: 'cron',
  })
  if (insertErr) {
    return { user_id: userId, status: 'error', reason: `db insert: ${insertErr.message}` }
  }

  // 10. Update profile timestamps
  const profileUpdate: Record<string, string> = {
    last_consulting_report_at: new Date().toISOString(),
  }
  if (reportType === 'welcome') {
    profileUpdate.welcome_report_at = new Date().toISOString()
  }
  await supabase.from('profiles').update(profileUpdate).eq('user_id', userId)

  // 11. SMS the contractor
  if (profile.owner_phone) {
    const fromNumber = profile.twilio_number || process.env.TWILIO_PHONE_NUMBER!
    const link = `https://www.bellavego.com/dashboard/reports/${reportId}`
    const totalUpside = report.opportunities.reduce((s, o) => s + o.monthlyValue, 0)
    const body =
      reportType === 'welcome'
        ? `${firstName}, your BellAveGo welcome report is ready. ~$${totalUpside.toLocaleString()}/mo in identified upside in your market. View: ${link}`
        : `${firstName}, your ${quarterLabel(windowEnd)} BellAveGo report is ready. ${report.opportunities[0]?.title || 'Top opportunity'} (~$${report.opportunities[0]?.monthlyValue.toLocaleString() || '0'}/mo). View: ${link}`
    try {
      await twilioClient.messages.create({ body, from: fromNumber, to: profile.owner_phone })
    } catch (e) {
      console.error('report SMS failed:', e)
      // Non-fatal — report still generated
    }
  }

  return { user_id: userId, status: 'generated', reportType, reportId, pdfUrl }
}

function splitFirstName(businessName: string): string {
  return businessName.split(/\s+/)[0] || 'there'
}

function quarterLabel(d: Date): string {
  const q = Math.floor(d.getMonth() / 3) + 1
  return `Q${q} ${d.getFullYear()}`
}

/** Defensible per-home-per-year trade spend estimates (industry averages). */
function tradeAnnualSpend(tradeRaw: string): number {
  const trade = tradeRaw.toLowerCase()
  if (trade.includes('hvac') || trade.includes('heating') || trade.includes('cooling')) return 280
  if (trade.includes('plumb')) return 220
  if (trade.includes('electr')) return 180
  if (trade.includes('roof')) return 320
  if (trade.includes('clean')) return 360
  if (trade.includes('lawn') || trade.includes('landscap')) return 480
  return 240 // generic home services
}
