import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import {
  LEADS_PER_WEEK,
  LEADS_PER_MONTH,
  PRICE_MONTHLY_USD,
  PRICE_ANNUAL_USD,
  PRICE_ANNUAL_SAVINGS_USD,
  INTRO_PRICE_USD,
  INTRO_PROMO_CODE,
  GUARANTEE_SHORT,
  GUARANTEE_HEADLINE,
  SUPPORTED_TRADES_SENTENCE,
  LEAD_SOURCES_HUMAN,
  LEAD_FIELDS_HUMAN,
  BRAND_NAME,
  FOUNDER_PHONE,
  FOUNDER_PHONE_HREF,
  META_TITLE,
  META_DESCRIPTION,
  SITE_URL,
} from '@/lib/offer'

/**
 * Homepage — 2026-06-09 leads-only rebuild per task 4 of the offer plan.
 *
 * RULES (enforced by reviewer in brief):
 *   - No invented testimonials, customer counts, ROI claims, or "exclusive"
 *     unless we can verify it from the codebase / paying customers
 *   - Describe leads HONESTLY per the real data sources (permit /
 *     property data prospects, NOT inbound calls)
 *   - [PETER: CONFIRM] placeholder for any claim that can't be verified
 *   - One CTA, single offer, ${LEADS_PER_WEEK}/wk reads from offer.ts
 *   - Server component (no 'use client') so headline + price + CTA appear
 *     in server-rendered HTML (Task 6 requirement)
 *
 * Structure:
 *   1. Nav
 *   2. Hero — headline + subhead + ONE CTA
 *   3. "What you get every Monday" — mirrors /sample-report
 *   4. Pricing card
 *   5. FAQ
 *   6. Founder footer
 */

export const metadata: Metadata = {
  title: META_TITLE,
  description: META_DESCRIPTION,
  alternates: { canonical: SITE_URL },
  openGraph: { title: META_TITLE, description: META_DESCRIPTION, url: SITE_URL, siteName: BRAND_NAME, type: 'website' },
  twitter: { card: 'summary_large_image', title: META_TITLE, description: META_DESCRIPTION },
}

const FAQS: { q: string; a: string }[] = [
  {
    q: 'What exactly is a "lead"?',
    a: `A homeowner in your service area who has shown a real intent signal in public records — a permit filed, a NOAA-verified storm strike on their block, a recent move-in, or an aging system flagged in county data. We deliver their name, street address, verified phone (skip-traced via BatchData), property year built + estimated value, and the specific signal that surfaced them.`,
  },
  {
    q: 'Are these leads exclusive?',
    a: '[PETER: CONFIRM — exclusivity guarantee] If you guarantee one shop per zip, write the policy here. The codebase does not currently enforce zip-locking. Leaving this question honest until the policy is documented.',
  },
  {
    q: 'How many leads do I actually get per week?',
    a: `${LEADS_PER_WEEK} per week, delivered to your dashboard Monday morning. That's about ${LEADS_PER_MONTH} per month. The current scraper output supports this volume per the 2026-06-09 supply audit.`,
  },
  {
    q: 'Do you call or text the homeowners for me?',
    a: 'No. We deliver the lead AND a pre-written outreach script (SMS + email + call opener) generated by AI based on your business profile. You choose how to reach out — call, text, email — your way. You control the relationship from first touch.',
  },
  {
    q: 'What is the guarantee?',
    a: GUARANTEE_SHORT,
  },
  {
    q: 'What if my zip code has no permit/storm/move-in data right now?',
    a: '[PETER: CONFIRM — empty-zip policy] The supply audit on 2026-06-09 shows Phoenix at 0 qualified leads in the last 6 weeks and most named Sun Belt metros at 0. If a customer signs up for a dry zip, what do we deliver?',
  },
  {
    q: 'Where do the names + phones come from? Is this legal?',
    a: 'All from public records. Building permits filed at city hall, county property records, MLS sold data, NOAA storm data. Skip-trace verification of phones via BatchData (the same provider used by ~70% of US real-estate wholesalers). All compliant w/ FCRA — homeowners on do-not-call lists are filtered.',
  },
  {
    q: 'How do I cancel?',
    a: 'In your dashboard, two clicks. No phone call. No retention loop. You keep every lead we sent you. If you cancel inside the first 30 days and we have not booked you a paying job, the refund is automatic.',
  },
]

export default function Home() {
  return (
    <main style={{ fontFamily: "'Inter', system-ui, sans-serif", background: '#FFF8F0', color: '#0B1F3A', minHeight: '100vh' }}>
      <Nav />
      <Hero />
      <WhatYouGetMonday />
      <PriceCard />
      <FaqSection />
      <FooterStrip />
    </main>
  )
}

function Nav() {
  return (
    <nav style={{
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      gap: 16,
      padding: 'clamp(8px, 1.5vw, 12px) clamp(16px, 4vw, 48px)',
      background: 'rgba(255,248,240,0.94)',
      borderBottom: '1px solid rgba(232,116,43,0.18)',
      position: 'sticky', top: 0, zIndex: 100,
    }}>
      <Link href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none', flexShrink: 0 }}>
        <Image src="/logo.png" alt={BRAND_NAME} width={300} height={92} style={{ objectFit: 'contain', maxWidth: 'min(50vw, 300px)', height: 'auto' }} priority />
      </Link>
      <div style={{ display: 'flex', gap: 14, alignItems: 'center', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
        <Link href="/founder" style={navLinkStyle}>Founder</Link>
        <Link href="/pricing" style={navLinkStyle}>Pricing</Link>
        <a href={FOUNDER_PHONE_HREF} style={{ ...navLinkStyle, color: '#C84B26' }}>{FOUNDER_PHONE}</a>
        <Link href="/sign-in" style={navLinkStyle}>Sign in</Link>
        <Link href={`/start?promo=${INTRO_PROMO_CODE}`} style={ctaPrimaryStyle}>${INTRO_PRICE_USD} first month →</Link>
      </div>
    </nav>
  )
}

function Hero() {
  return (
    <section style={{ padding: 'clamp(36px, 6vw, 80px) clamp(16px, 5vw, 48px) clamp(28px, 4vw, 56px)' }}>
      <div style={{ maxWidth: 920, margin: '0 auto', textAlign: 'center' }}>
        <h1 style={{
          fontSize: 'clamp(34px, 5.4vw, 60px)',
          fontWeight: 900, letterSpacing: '-0.045em', lineHeight: 1.04,
          margin: '0 0 18px',
        }}>
          <span style={{
            background: 'linear-gradient(135deg, #FF9D5A 0%, #E8742B 60%, #C84B26 100%)',
            WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent',
          }}>{LEADS_PER_WEEK} fresh leads</span> in your service area every week.
        </h1>
        <p style={{ fontSize: 'clamp(16px, 1.6vw, 19px)', color: '#3D5A66', lineHeight: 1.55, margin: '0 auto 28px', maxWidth: 680 }}>
          <strong style={{ color: '#0B1F3A' }}>${PRICE_MONTHLY_USD}/mo, first month ${INTRO_PRICE_USD}</strong>, cancel anytime. Built for {SUPPORTED_TRADES_SENTENCE}.
        </p>
        <Link href={`/start?promo=${INTRO_PROMO_CODE}`} style={ctaHeroStyle}>
          Start ${INTRO_PRICE_USD} trial → lock my zip
        </Link>
        <p style={{ margin: '14px 0 0', fontSize: 13, color: '#7AAAB2' }}>
          90-second checkout · {GUARANTEE_HEADLINE}
        </p>
      </div>
    </section>
  )
}

function WhatYouGetMonday() {
  return (
    <section style={{
      padding: 'clamp(32px, 5vw, 64px) clamp(16px, 5vw, 48px)',
      background: '#FFFFFF',
      borderTop: '1px solid rgba(232,116,43,0.12)',
      borderBottom: '1px solid rgba(232,116,43,0.12)',
    }}>
      <div style={{ maxWidth: 920, margin: '0 auto' }}>
        <h2 style={{
          fontSize: 'clamp(24px, 3.2vw, 38px)', fontWeight: 900,
          letterSpacing: '-0.03em', lineHeight: 1.1, margin: '0 0 14px', textAlign: 'center',
        }}>What lands in your inbox every Monday</h2>
        <p style={{ fontSize: 15, color: '#4A6670', textAlign: 'center', maxWidth: 620, margin: '0 auto 32px', lineHeight: 1.55 }}>
          {LEADS_PER_WEEK} prospect homeowners pulled overnight from public records in your service area. Every lead is sourced from a real signal — no random scrapes, no shared HomeAdvisor pool.
        </p>
        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 18, marginBottom: 28,
        }}>
          <div style={cardWhitePanel}>
            <div style={cardSubhead}>Where the data comes from</div>
            <ul style={cardList}>
              {LEAD_SOURCES_HUMAN.map((s) => <li key={s}>{s}</li>)}
            </ul>
          </div>
          <div style={cardWhitePanel}>
            <div style={cardSubhead}>Each lead contains</div>
            <ul style={cardList}>
              {LEAD_FIELDS_HUMAN.map((f) => <li key={f}>{f}</li>)}
            </ul>
          </div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <Link href="/sample-report" style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '12px 22px', borderRadius: 11,
            background: '#FFF8F0', color: '#C84B26',
            border: '1.5px solid #E8742B',
            textDecoration: 'none', fontWeight: 800, fontSize: 14,
          }}>See a redacted sample of your Monday inbox →</Link>
        </div>
      </div>
    </section>
  )
}

function PriceCard() {
  return (
    <section style={{ padding: 'clamp(40px, 5vw, 72px) clamp(16px, 5vw, 48px)' }}>
      <div style={{ maxWidth: 580, margin: '0 auto' }}>
        <div style={{
          background: 'linear-gradient(165deg, #FFFFFF 0%, #FFF8F0 100%)',
          borderRadius: 22,
          border: '2px solid #E8742B',
          padding: 'clamp(28px, 4vw, 40px)',
          boxShadow: '0 26px 70px rgba(232,116,43,0.16)',
          textAlign: 'center',
        }}>
          <div style={{
            display: 'inline-block', padding: '5px 14px', borderRadius: 99,
            background: 'linear-gradient(135deg, #22C55E, #16803F)',
            color: '#fff', fontSize: 10.5, fontWeight: 900, letterSpacing: '0.12em', textTransform: 'uppercase',
            marginBottom: 14,
          }}>
            First month w/ code {INTRO_PROMO_CODE}
          </div>
          <div style={{
            fontSize: 'clamp(64px, 11vw, 104px)', fontWeight: 900,
            letterSpacing: '-0.04em', lineHeight: 0.95,
            background: 'linear-gradient(135deg, #22C55E 0%, #16803F 100%)',
            WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent',
          }}>${INTRO_PRICE_USD}</div>
          <p style={{ fontSize: 14.5, color: '#0B1F3A', margin: '6px 0 4px', fontWeight: 600 }}>
            first month, then <strong>${PRICE_MONTHLY_USD}/mo</strong>
          </p>
          <p style={{ fontSize: 12.5, color: '#7AAAB2', margin: '0 0 22px' }}>
            Or ${PRICE_ANNUAL_USD.toLocaleString()}/yr — save ${PRICE_ANNUAL_SAVINGS_USD} · Cancel anytime
          </p>

          <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 22px', display: 'grid', gap: 8, textAlign: 'left' }}>
            {[
              `${LEADS_PER_WEEK} prospect homeowners / week (${LEADS_PER_MONTH}/month)`,
              'Verified phone per lead (skip-traced via BatchData)',
              'Pre-written outreach script per lead (SMS + email + call opener)',
              'Per-lead AI score (0-100) on intent + ticket size',
              'Dashboard, mobile-friendly, no integration required',
              GUARANTEE_HEADLINE,
            ].map((line) => (
              <li key={line} style={{ display: 'flex', alignItems: 'flex-start', gap: 9, fontSize: 14, lineHeight: 1.5 }}>
                <span style={{
                  flexShrink: 0, marginTop: 4, width: 16, height: 16, borderRadius: 5,
                  background: 'linear-gradient(135deg, #22C55E, #14B8A6)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <svg width="10" height="10" viewBox="0 0 16 16" fill="none" stroke="#fff" strokeWidth={3} strokeLinecap="round" strokeLinejoin="round">
                    <path d="M3 8.5l3.5 3.5 6.5-7" />
                  </svg>
                </span>
                <span style={{ color: '#0B1F3A' }}>{line}</span>
              </li>
            ))}
          </ul>

          <Link href={`/start?promo=${INTRO_PROMO_CODE}`} style={{
            ...ctaHeroStyle, width: '100%', justifyContent: 'center',
            display: 'inline-flex',
          }}>
            Start ${INTRO_PRICE_USD} trial — lock my zip →
          </Link>

          <p style={{ fontSize: 11.5, color: '#7AAAB2', margin: '14px 0 0' }}>
            90-second checkout · Card collected upfront · Powered by Stripe
          </p>
        </div>
      </div>
    </section>
  )
}

function FaqSection() {
  return (
    <section style={{ padding: 'clamp(40px, 5vw, 64px) clamp(16px, 5vw, 48px)' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <h2 style={{
          fontSize: 'clamp(22px, 2.8vw, 32px)', fontWeight: 900,
          letterSpacing: '-0.02em', margin: '0 0 28px', textAlign: 'center',
        }}>Real questions before you sign up</h2>
        <div style={{ display: 'grid', gap: 10 }}>
          {FAQS.map((f) => (
            <details key={f.q} style={{
              padding: '14px 18px', borderRadius: 13,
              background: '#FFFFFF',
              border: '1px solid rgba(232,116,43,0.18)',
              boxShadow: '0 4px 14px rgba(11,31,58,0.04)',
            }}>
              <summary style={{ cursor: 'pointer', fontWeight: 800, color: '#0B1F3A', fontSize: 15 }}>{f.q}</summary>
              <p style={{ fontSize: 14, color: '#4A6670', lineHeight: 1.65, margin: '10px 0 0' }}>{f.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  )
}

function FooterStrip() {
  return (
    <footer style={{ padding: '32px 24px', background: '#0B1F3A', textAlign: 'center', color: '#FFF8F0' }}>
      <Image src="/logo.png" alt={BRAND_NAME} width={220} height={68} style={{ objectFit: 'contain', filter: 'brightness(1.2)', marginBottom: 8 }} />
      <p style={{ margin: '4px 0', fontSize: 12, color: '#7AAAB2' }}>
        Contractor lead-gen for {SUPPORTED_TRADES_SENTENCE} · Cancel anytime
      </p>
      <p style={{ margin: '12px 0 0', fontSize: 11, color: 'rgba(255,255,255,0.40)' }}>
        <Link href="/founder" style={{ color: '#FF9D5A', textDecoration: 'none' }}>Founder</Link>
        {' · '}
        <Link href="/pricing" style={{ color: '#5EEAD4', textDecoration: 'none' }}>Pricing</Link>
        {' · '}
        <Link href="/sample-report" style={{ color: '#5EEAD4', textDecoration: 'none' }}>Sample Monday inbox</Link>
        {' · '}
        <a href={FOUNDER_PHONE_HREF} style={{ color: '#FF9D5A', textDecoration: 'none' }}>{FOUNDER_PHONE}</a>
        {' · '}
        <Link href="/privacy" style={{ color: '#5EEAD4', textDecoration: 'none' }}>Privacy</Link>
        {' · '}
        <Link href="/terms" style={{ color: '#5EEAD4', textDecoration: 'none' }}>Terms</Link>
        {' · '}© 2026 {BRAND_NAME} LLC
      </p>
    </footer>
  )
}

const navLinkStyle: React.CSSProperties = {
  color: '#0B1F3A', textDecoration: 'none', fontWeight: 800, fontSize: 15,
}

const ctaPrimaryStyle: React.CSSProperties = {
  display: 'inline-flex', alignItems: 'center', gap: 6,
  padding: '12px 20px', borderRadius: 11,
  background: 'linear-gradient(135deg, #FF9D5A 0%, #E8742B 100%)',
  color: '#fff', textDecoration: 'none',
  fontWeight: 900, fontSize: 15,
  boxShadow: '0 8px 22px rgba(232,116,43,0.36)',
}

const ctaHeroStyle: React.CSSProperties = {
  display: 'inline-flex', alignItems: 'center', gap: 8,
  padding: '17px 32px', borderRadius: 14,
  background: 'linear-gradient(135deg, #FF9D5A 0%, #E8742B 50%, #C84B26 100%)',
  color: '#fff', textDecoration: 'none',
  fontWeight: 900, fontSize: 16, letterSpacing: '-0.01em',
  boxShadow: '0 14px 36px rgba(232,116,43,0.40)',
}

const cardWhitePanel: React.CSSProperties = {
  padding: 'clamp(16px, 2vw, 22px)',
  borderRadius: 13,
  background: '#FFF8F0',
  border: '1px solid rgba(232,116,43,0.20)',
}

const cardSubhead: React.CSSProperties = {
  fontSize: 11, fontWeight: 900, color: '#C84B26',
  letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 8,
}

const cardList: React.CSSProperties = {
  margin: 0, padding: '0 0 0 18px',
  fontSize: 14, color: '#0B1F3A', lineHeight: 1.65,
}
