-- Social posts log
-- =====================================================================
-- Tracks every post the daily content cron generates + queues via Zernio.
-- Used to:
--   1. Avoid repeating the same theme too close together (history check)
--   2. Audit what's been posted on each platform
--   3. Detect when Zernio publishing fails so we can retry/alert
--
-- IDEMPOTENT: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS social_posts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Theme ID from CONTENT_THEMES in src/lib/socialContentGenerator.ts
  theme           TEXT NOT NULL,
  caption         TEXT NOT NULL,
  scheduled_for   TIMESTAMPTZ NOT NULL,
  -- Comma-separated Zernio account IDs the post was sent to
  account_ids     TEXT,
  -- Zernio's response (post _id, etc.) or error message
  zernio_response JSONB,
  -- 'queued' / 'posted' / 'failed'
  status          TEXT NOT NULL DEFAULT 'queued'
);

CREATE INDEX IF NOT EXISTS social_posts_created_idx ON social_posts (created_at DESC);
CREATE INDEX IF NOT EXISTS social_posts_theme_idx ON social_posts (theme, created_at DESC);

COMMENT ON TABLE social_posts IS
  'Log of posts generated by /api/crons/social-content-daily and queued via Zernio. '
  'Lets the next day''s cron avoid repeating recent themes + audit failures.';
