-- Per-lead personalized opener — 1-2 line hook generated by Sonnet from
-- website snippet + business name + city + review count. Used as
-- {{personalized_opener}} merge tag in cold email Step 0.

ALTER TABLE outreach_leads ADD COLUMN IF NOT EXISTS personalized_opener text;
ALTER TABLE outreach_leads ADD COLUMN IF NOT EXISTS personalized_opener_generated_at timestamptz;

CREATE INDEX IF NOT EXISTS outreach_leads_needs_personalization_idx
  ON outreach_leads (status, personalized_opener_generated_at)
  WHERE personalized_opener_generated_at IS NULL AND email IS NOT NULL;
