-- 2026-06-04 — Neighborhood Lead Engine
--
-- Per Peter's pivot: BellAveGo's reports are now "Neighborhood Lead Reports"
-- that deliver real prospect leads (move-ins, building permits, storm
-- triggers, aging-infrastructure homes) to each customer's dashboard at the
-- cadence defined by their tier:
--   Starter → 5 leads/quarter (20/year)
--   Pro     → 15 leads/month  (180/year)
--   Elite   → 25 leads/week   (~1,300/year)
--
-- Two tables:
--   leads        — every lead ever ingested (one row per address, dedup'd)
--   lead_drops   — per-tenant assignments of leads to customers, with
--                  the cadence quota tracking (5/qtr, 15/mo, 25/wk)

-- ── leads ────────────────────────────────────────────────────────
-- Master pool of leads ingested from data sources.
-- Source types: 'move_in', 'permit', 'storm', 'aging_hvac', 'expired_listing'
create table if not exists leads (
  id                uuid primary key default gen_random_uuid(),
  -- Geography
  zip               text not null,
  city              text,
  state             text,
  street_address    text,
  lat               numeric(10, 6),
  lng               numeric(10, 6),
  -- Owner info (when available — varies by source)
  owner_name        text,
  owner_phone       text,
  owner_email       text,
  -- Home details (from property records / Census)
  home_value_est    integer,
  year_built        integer,
  sqft              integer,
  bedrooms          smallint,
  bathrooms         smallint,
  -- Source + scoring
  source            text not null check (source in ('move_in', 'permit', 'storm', 'aging_hvac', 'expired_listing', 'other')),
  source_event_date timestamptz,
  source_details    jsonb,
  -- AI scoring 0-100; 100 = highest intent
  lead_score        smallint default 50,
  score_reasoning   text,
  -- One-line pitch script generated by Claude for the lead context
  pitch_script      text,
  -- Trade match: which trade(s) this lead fits ('hvac', 'plumbing', etc.)
  trade_match       text[],
  -- Lifecycle
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  -- Dedup key: same address + same source = same lead
  unique (street_address, source)
);

create index if not exists leads_zip_idx on leads (zip);
create index if not exists leads_source_idx on leads (source);
create index if not exists leads_score_idx on leads (lead_score desc);
create index if not exists leads_trade_idx on leads using gin (trade_match);

-- ── lead_drops ───────────────────────────────────────────────────
-- Assignment of leads to specific customers. The lead-engine cron fills
-- this table per tier cadence. The dashboard "Leads" tab reads from here.
create table if not exists lead_drops (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null,
  profile_id        uuid not null,
  lead_id           uuid not null references leads(id) on delete cascade,
  -- Drop period for quota enforcement
  drop_date         date not null default current_date,
  -- 'quarterly' | 'monthly' | 'weekly' — keyed to the tier at drop time
  drop_period       text not null,
  -- Lifecycle (the customer's view of this lead)
  status            text not null default 'new' check (
    status in ('new', 'viewed', 'contacted', 'quoted', 'won', 'lost', 'dismissed')
  ),
  status_updated_at timestamptz,
  notes             text,
  created_at        timestamptz not null default now(),
  -- Same lead can't be dropped to the same tenant twice (dedup)
  unique (user_id, lead_id)
);

create index if not exists lead_drops_user_idx
  on lead_drops (user_id, drop_date desc);
create index if not exists lead_drops_status_idx
  on lead_drops (user_id, status);

-- ── Helper view: quota usage per tenant ──────────────────────────
-- Lets the lead-engine cron quickly check "did this tenant already receive
-- their 5 leads this quarter / 15 this month / 25 this week?"
create or replace view tenant_lead_quota_usage as
select
  user_id,
  count(*) filter (where drop_date >= date_trunc('quarter', current_date)) as leads_this_quarter,
  count(*) filter (where drop_date >= date_trunc('month',   current_date)) as leads_this_month,
  count(*) filter (where drop_date >= date_trunc('week',    current_date)) as leads_this_week,
  count(*) as leads_lifetime
from lead_drops
group by user_id;
